#configs for local env: mysql database
spring:
  application:
    name: Department Management
  datasource:
    password: password
    url: jdbc:mysql://localhost:3306/department_management_db
    username: root
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true

#Spring Boot actuator config
management:
  endpoints:
    web:
      exposure:
        include: "*"