server:
  port: 8080
spring:
  application:
    name: Department Management
  datasource:
    driverClassName: org.h2.Driver
    password: password
    url: jdbc:h2:mem:department_management_db
    username: sa
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
#  datasource:
#    password: password
#    url: jdbc:mysql://localhost:3306/department_management_db
#    username: root
#  jpa:
#    hibernate:
#      ddl-auto: update
#      show-sql: true
welcome:
  message: "Welcome to Department Management Spring boot Application"
