#configs for prod env
spring:
  application:
    name: Department Management
  datasource:
    password: password
    url: jdbc:mysql://localhost:3306/department_management_db
    username: root
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true